### ISSUE TITLE
Compat issue with Fabric builds

### ISSUE THREAD

**Issue by Sunconure11** [Tsukimi-Ren/Casualness-Delight#3] opened 2023-08-12 21:33 UTC
https://gist.github.com/Sunconure11/3037cfa4fc0808293ca904c8df634ce8

**Comment by Sunconure11** [comment] 2023-08-12 23:40
The issue seems to be related to usage of Quilt.

@Tsukimi-Ren

**Comment by Tsukimi-Ren** [comment] 2023-08-13 16:11
ummm,This was caused by an oversight during the previous upload,Now fixed，Please download again on modrinth

**Closed by Tsukimi-Ren** 2023-08-13 16:11 UTC

**Comment by Sunconure11** [comment] 2023-08-13 18:44
Has the build even been approved? I don’t see any… difference.

**Comment by Tsukimi-Ren** [comment] 2023-08-14 03:44
Because the content has not changed，So I just replaced the fabric version of the file and didn't create a new version
